### PR TITLE
Save responses

### PR DESCRIPTION
**Pull request by aguilerapy**
Uganda API could return the package with empty release list, anyway I saved it. #328

### CODE REVIEW

**Comment by jpmckinney** [comment]
Actually, taking a step back, in what case does it have an empty release list?

**Comment by aguilerapy** [comment]
Examples for this empty list case:

- https://gpp.ppda.go.ug/adminapi/public/api/open-data/v1/releases/award?fy=2014-2015&pde=375
- https://gpp.ppda.go.ug/adminapi/public/api/open-data/v1/releases/contract?fy=2019-2020&pde=684
- https://gpp.ppda.go.ug/adminapi/public/api/open-data/v1/releases/award?fy=2019-2020&pde=450

**Comment by jpmckinney** [comment]
Aha, so some public entities just don't have any contracts. I think it's fine to save them without filtering them out like in the PR.

**Comment by jpmckinney** [comment]
Thanks for the review, @yolile. Please delete branches after merging, to keep GitHub tidy :)

**Comment by yolile** [comment]
@jpmckinney sure! I thought that the branches were auto deleted after merged but it seems that is not the case, so I will delete it by myself the next time

**Comment by jpmckinney** [comment]
I just double-checked, and I see that there is a "Automatically delete head branches" option, which I've now enabled, so we don't need to manually delete branches :)

**Pull request merged**
