### PR TITLE
add proxy option to scrapers

### PR DESCRIPTION
**Pull request by kindly**
Add a proxy option to kingfisher scrape.

### CODE REVIEW

**Comment by odscjames** [comment]
Haven't tested but on reading it looks good. 

My only comment is that the Hosted docs will say "You can do this!" and you won't be able to because the other half of the system (the actual Proxy and the KINGFISHER_PROXY_URL setting) won't have been done.

Could we put that in the docs hosted page but commented out for now? Then it's ready to go later. But I think the immediate user need has been cleared, so it may be a while before the other bit of work is prioritised.

Also that could go in the docs for the other pages - Standalone and Scrapyd - right now.

**Comment by kindly** [comment]
@odscjames 

The proxy and the the KINGFISHER_PROXY_URL have beed deployed and are ready.  I thought I would do that first for the above reason.

So as soon as this pull request is merged and deployed the docs will work.

I have also just now added docs for the standalone a scrapyd parts.

**Comment by odscjames** [comment]
I am minded to close this as having been superseded by #235 

It does do things in a different way, and if we use Proxies more in the future we may want to come back to this and work out which way is best. But for now, am closing.

**Comment by jpmckinney** [comment]
I've removed the configuration that was added to deploy in September, to avoid future confusion.

**Pull request closed without merging**
