### PR TITLE
Change to correct license

### PR DESCRIPTION
**Pull request by odscjames**
https://github.com/open-contracting/kingfisher-scrape/issues/28

### CODE REVIEW

**Comment by odscjames** [comment]
@jpmckinney This is what has been used before so I think it's correct - can you confirm?

**Comment by jpmckinney** [comment]
Yes - BSD-3 for Python code. I usually just put the first year, to avoid having to continuously change the end year.

**Comment by odscjames** [comment]
Just had a quick Google (I thought putting the end year was recommended but apparently it's all a bit more complicated than that). I put it back to just start year then.

**Comment by jpmckinney** [comment]
Updating the end year is generally only important for extending the copyright period, which isn't something we're interested in protecting (falling into public domain is fine).

**Pull request merged**
