### PR TITLE
Update Paraguay DNCP scrapers for new API

### PR DESCRIPTION
**Pull request by romifz**
#218

### CODE REVIEW

**Comment by odscjames** [comment]
Did you know you can pass meta information with a request? https://github.com/open-contracting/kingfisher-scrape/blob/edf696807f5fe9027ec1cee50099d56ce92f9712/kingfisher_scrapy/spiders/moldova.py#L50 See use of the 'page' variable there. This might be able to replace the regular expression to get the page number from the URL.

**Comment by odscjames** [comment]
But that is just a note for future work, feel free to merge now if you want.

**Comment by romifz** [comment]
Thank you James! I noticed a mistake in the regular expression, it's fixed now. BTW I knew about the meta attribute in requests, I just like regular expressions 😅.

I just deleted a single character in a file, so I'll ask @yolile for approval to merge.

**Comment by jpmckinney** [comment]
@romifz Can we [`urllib.parse`](https://docs.python.org/3/library/urllib.parse.html) the page, instead of using regular expressions? Regexes should only be used if there isn't a better way to parse a string.

**Pull request merged**
