### PR TITLE
Remove collectioninfo files

### PR DESCRIPTION
**Pull request by jpmckinney**
Includes #274 to avoid a merge conflict.

#275 indicated that no one uses the `*.collectioninfo` files (or knew they existed).

The source, data version, and sample status are already represented in the file path (`<source>[_sample]/<data_version>`). The fact that the spider finished (previously represented by the existence of `kingfisher-finished.collectioninfo`) is already represented in the crawl log.

After this PR, the note and end time won't be represented anywhere on the filesystem, but, from Kingfisher Scrape's perspective, I don't think we care that much about notes (most are just who started the scrape) or the end time (#275 suggested they could just be recorded as crawl stats). 

The note and end time are still sent to Kingfisher Process, where we do care about them.

### CODE REVIEW

**Comment by jpmckinney** [comment]
[Kingfisher Scrape Pull Requests](https://trello.com/c/3UJxS3mQ/184-kingfisher-scrape-pull-requests)

**Comment by odscjames** [comment]
I commented on #275 with my purpose in adding these

**Comment by odscjames** [comment]
Following the discussion in #275, I'd question whether this should be done yet.

#308 isn't done yet, and until it does we could lose some info if trying to restore, such as whether a scrape actually finished successfully or not. Maybe not much info, but given that it's only 2 small files on disk it doesn't seem worth rushing to remove them. The code is nicely in the base_spider.py alongside the code for writing the actual data to disk, so it's not too messy.

But I can review if you want to progress now - I think a rebase is needed first tho.

**Comment by jpmckinney** [comment]
Let's merge it as the spider shouldn't be writing files to disk (continued in #277), since doing so circumvents the item pipeline entirely, which prevents us from taking advantage of Scrapy features that would be helpful in closing some other issues e.g. #283 #84.

#308 is easy to close, and I don't anticipate we'll delete log files or kill the server before we back them up.

**Comment by yolile** [comment]
@jpmckinney the test coverage decreased

**Comment by jpmckinney** [comment]
@yolile Yes, that's because we're deleting code that was tested, so the total coverage is dropping down closer to the average.

**Pull request merged**
